### ISSUE TITLE
Plotting Functions have stale dependencies

### ISSUE THREAD

**Issue by iffthomas** [fortuinlab/LA-NAM#1]
Hi all,
Thank you for publishing the code I saw the paper and was quite interested in implementing and testing this method myself.
Unfortunately I think something is not right with the automatic installation of the sklearn package when trying to install
`pip install git+https://github.com/fortuinlab/LA-NAM.git`
More specifically, when i create a new environment and install the package I can run the la-nam. However when trying to call this line
`from laplace_skorch.inspection import subnetwork_outputs_for_X, subnetwork_covar_for_X`
I get the following error:

> Traceback (most recent call last):
  File "nam_iris.py", line 52, in <module>
    from laplace_skorch.inspection import subnetwork_outputs_for_X, subnetwork_covar_for_X
  File "/C:/Users/ifft/miniforge3/envs/newenv/lib/python3.11/site-packages/laplace_skorch/inspection.py", line 13, in <module>
    from sklearn.utils import _get_column_indices, _safe_indexing, check_matplotlib_support
ImportError: cannot import name '_get_column_indices' from 'sklearn.utils' (/C:/Users/ifft/miniforge3/envs/newenv/lib/python3.11/site-packages/sklearn/utils/__init__.py)

I've looked up when this function was actively used and it seems that it was used in sklearn < 1.5
When i then want to downgrade it it doesnt work as other dependencies aren't compatible with a lower version of sklearn.

What would you suggest as a workaround for leveraging the plotting functions?

**Comment by iffthomas** [comment]
#downgrading scikit-learn to 1.4 resolved the issue

**Comment by kourbou** [comment]
Ah yes, seems that this private API was split up into submodules in `scikit-learn >= 1.5.0`. I pushed a fix and added a dependency on that version or above.

Thanks for testing our project! Let me know if this fixes the fresh install for you. (If not I'll re-open.)
